import { Course } from './models/course';
export const courseList: Course[] = [
  {
    id: 1,
    title: 'Introduction to JavaScript',
    url: 'images/1.png',
    price: '$19.99',
    content:
      'Learn the basics of JavaScript, the most popular programming language.',
    createdAt: '2024-01-01',
    publishedAt: '2024-01-05',
    active: false,
  },
  {
    id: 2,
    title: 'Advanced TypeScript',
    url: 'images/2.png',
    price: '$29.99',
    content:
      'Master advanced features of TypeScript to enhance your coding skills.',
    createdAt: '2024-01-10',
    publishedAt: '2024-01-15',
    active: false,
  },
  {
    id: 3,
    title: 'Web Development Bootcamp',
    url: 'images/3.png',
    price: '$49.99',
    content:
      'Become a full-stack web developer with this comprehensive bootcamp.',
    createdAt: '2024-01-20',
    publishedAt: '2024-01-25',
    active: false,
  },
  {
    id: 4,
    title: 'React for Beginners',
    url: 'images/4.png',
    price: '$25.99',
    content:
      'Learn how to build dynamic and modern web applications with React.',
    createdAt: '2024-01-05',
    publishedAt: '2024-01-15',
    active: true,
  },
  {
    id: 5,
    title: 'Node.js Essentials',
    url: 'images/5.png',
    price: '$35.99',
    content: 'Get started with backend development using Node.js.',
    createdAt: '2024-01-08',
    publishedAt: '2024-01-12',
    active: true,
  },
  {
    id: 6,
    title: 'CSS Flexbox and Grid',
    url: 'images/6.png',
    price: '$15.99',
    content: 'Master layout techniques with CSS Flexbox and Grid.',
    createdAt: '2024-01-15',
    publishedAt: '2024-01-15',
    active: true,
  },
  {
    id: 7,
    title: 'Python for Data Science',
    url: 'images/7.png',
    price: '$59.99',
    content:
      'Explore data science with Python, including libraries like Pandas and NumPy.',
    createdAt: '2024-01-18',
    publishedAt: '2024-01-20',
    active: false,
  },
  {
    id: 8,
    title: 'Machine Learning Basics',
    url: 'images/8.png',
    price: '$99.99',
    content: 'An introduction to machine learning concepts and techniques.',
    createdAt: '2024-01-15',
    publishedAt: '2024-01-15',
    active: true,
  },
  {
    id: 9,
    title: 'SEO Strategies 2024',
    url: 'images/9.png',
    price: '$19.99',
    content:
      'Learn the latest SEO strategies to rank higher in search engines.',
    createdAt: '2024-01-22',
    publishedAt: '2024-01-28',
    active: true,
  },
  {
    id: 10,
    title: 'DevOps for Beginners',
    url: 'images/10.png',
    price: '$39.99',
    content:
      'Understand the basics of DevOps and continuous integration/delivery.',
    createdAt: '2024-01-12',
    publishedAt: '2024-01-14',
    active: false,
  },
];
